cursor #dfe3e7
cursor_text_color #c0c7cd

foreground            #dfe3e7
background            #0f1417
selection_foreground  #1f333d
selection_background  #b5c9d7
url_color             #8ecff2

color0   #0f1417
color1   #ff729f
color2   #79f287
color3   #fff672
color4   #73bee5
color5   #1b5270
color6   #8ecff2
color7   #eef8fe
color8   #91999d
color9   #ff9fbd
color10  #a5ffb0
color11  #fff9a5
color12  #a5dfff
color13  #b5e5ff
color14  #cfeeff
color15  #f8fcff
