cursor #dee3e6
cursor_text_color #c0c8cc

foreground            #dee3e6
background            #0f1416
selection_foreground  #1e333c
selection_background  #b3cad5
url_color             #89d0ed

color0   #0f1416
color1   #ff72a0
color2   #76ed83
color3   #fff672
color4   #6fc0e1
color5   #18556d
color6   #89d0ed
color7   #e9f4f8
color8   #8e969a
color9   #ff9fbe
color10  #a5ffaf
color11  #fff9a5
color12  #a3e4ff
color13  #b3e9ff
color14  #cef0ff
color15  #f8fdff
