# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

continuation_prompt = '▶▶ '

[c]
format = 'via [$name $version]($style)'

[character]
success_symbol = '[➜](bold green) '
error_symbol = '[✗](bold red) '
vimcmd_symbol = '[V](bold green) '

[container]
format = '[$symbol \[$name\]]($style) '